### ISSUE TITLE
Tracking issue for modernization efforts

### ISSUE THREAD

**Issue by regexident** [mattt/Surge#106]
Hi Matt,

I'd like to contribute a series of improvements to Surge.

**Surge** is already pretty nice for implementing performant number crunching and machine learning algorithms, but I find myself writing my own `Vector<Scalar>` types and adding extensions for common `Matrix<Scalar>` operations over and over again (especially the scalar variants), so I figured I might as well upstream them:

- [x] Upgrade to recommended project settings. (https://github.com/mattt/Surge/pull/109)
- [x] Add overload of `XCTAssertEqual(_:_:accuracy:)` for collections of `FloatingPoint`. (https://github.com/mattt/Surge/pull/104)
- [x] Add basic suite of unit tests for arithmetic functions. (https://github.com/mattt/Surge/pull/105)
- [x] Add basic suite of unit tests for matrix arithmetic functions. (https://github.com/mattt/Surge/pull/108)
- [x] Add missing named function equivalents of `.`-operators (e.g. `addInPlace(_:_:)` for `.+=(_:_:)`), transforming operators into strictly forwarding calls of explicitly named equivalents. (https://github.com/mattt/Surge/pull/107)
- [x] Add Matrix initializers for common diagonal/eye/identity patterns. (https://github.com/mattt/Surge/pull/111)
- [x] Optimize scalar-variants of arithmetic functions (e.g. `func mul(x: [Float], y: Float)`, etc.) where applicable.
- [x] Add missing scalar-variants of matrix functions (e.g. `func mul(x: Matrix<Float>, y: Float)`, etc.). (https://github.com/mattt/Surge/pull/110)
- [x] Add `Vector<Scalar>` type and unit tests for performant, yet expressive vector arithmetic. (https://github.com/mattt/Surge/pull/110)
- [x] Add matrix-vector multiplication and other arithmetic functions (using `Matrix<Scalar>` & `Vector<Scalar>`). (https://github.com/mattt/Surge/pull/110)

---

### Why `Vector<Scalar>` if we already have `[Scalar]`?

Simply using `[Float]` requires one to use `.+` & Co, due to otherwise colliding with array concatenation, etc. Having an explicit `Vector<Scalar>` type also allows for better auto-completion by keeping all the non-vector-space-related `Array`/`Collection` gunk out of it. Or and it also doesn't spill every operator/function into the global namespace of `Collection`.
